### ISSUE TITLE
mp3 streams have glitches

### ISSUE THREAD

**Issue by nfs22** [kimmoli/sfos-onyx-issues#54] opened 2018-04-17 21:05 UTC
i tried different players (allradio, sailwave, native jolla player) all of them have to issue to have glitcher (small interrupts in playback)

**Comment by rinigus** [comment] 2018-04-18 19:33
Can you send a sample MP3 stream URL?

**Comment by rinigus** [comment] 2018-04-21 07:11
I tested on few online radio stations and cannot reproduce it. Unless we get some specific example, I suggest to close it

**Closed as completed** 2018-09-30 20:13 UTC
